//! Host 模式 IDT stub，与 `hv/hv/interrupt-handlers.asm` 同构。

use core::arch::global_asm;

global_asm!(
    ".text",
    "host_generic_interrupt:",
    "sub rsp, 0x78",
    "mov [rsp + 0x00], rax",
    "mov [rsp + 0x08], rcx",
    "mov [rsp + 0x10], rdx",
    "mov [rsp + 0x18], rbx",
    "mov [rsp + 0x20], rbp",
    "mov [rsp + 0x28], rsi",
    "mov [rsp + 0x30], rdi",
    "mov [rsp + 0x38], r8",
    "mov [rsp + 0x40], r9",
    "mov [rsp + 0x48], r10",
    "mov [rsp + 0x50], r11",
    "mov [rsp + 0x58], r12",
    "mov [rsp + 0x60], r13",
    "mov [rsp + 0x68], r14",
    "mov [rsp + 0x70], r15",
    "mov rcx, rsp",
    "sub rsp, 0x20",
    "call {dispatch}",
    "add rsp, 0x20",
    "mov rax, [rsp + 0x00]",
    "mov rcx, [rsp + 0x08]",
    "mov rdx, [rsp + 0x10]",
    "mov rbx, [rsp + 0x18]",
    "mov rbp, [rsp + 0x20]",
    "mov rsi, [rsp + 0x28]",
    "mov rdi, [rsp + 0x30]",
    "mov r8,  [rsp + 0x38]",
    "mov r9,  [rsp + 0x40]",
    "mov r10, [rsp + 0x48]",
    "mov r11, [rsp + 0x50]",
    "mov r12, [rsp + 0x58]",
    "mov r13, [rsp + 0x60]",
    "mov r14, [rsp + 0x68]",
    "mov r15, [rsp + 0x70]",
    "add rsp, 0x78",
    "add rsp, 8",
    "add rsp, 8",
    "iretq",
    ".globl host_isr_0",
    "host_isr_0:",
    "push 0",
    "push 0",
    "jmp host_generic_interrupt",
    ".globl host_isr_1",
    "host_isr_1:",
    "push 0",
    "push 1",
    "jmp host_generic_interrupt",
    ".globl host_isr_2",
    "host_isr_2:",
    "push 0",
    "push 2",
    "jmp host_generic_interrupt",
    ".globl host_isr_3",
    "host_isr_3:",
    "push 0",
    "push 3",
    "jmp host_generic_interrupt",
    ".globl host_isr_4",
    "host_isr_4:",
    "push 0",
    "push 4",
    "jmp host_generic_interrupt",
    ".globl host_isr_5",
    "host_isr_5:",
    "push 0",
    "push 5",
    "jmp host_generic_interrupt",
    ".globl host_isr_6",
    "host_isr_6:",
    "push 0",
    "push 6",
    "jmp host_generic_interrupt",
    ".globl host_isr_7",
    "host_isr_7:",
    "push 0",
    "push 7",
    "jmp host_generic_interrupt",
    ".globl host_isr_8",
    "host_isr_8:",
    "push 8",
    "jmp host_generic_interrupt",
    ".globl host_isr_10",
    "host_isr_10:",
    "push 10",
    "jmp host_generic_interrupt",
    ".globl host_isr_11",
    "host_isr_11:",
    "push 11",
    "jmp host_generic_interrupt",
    ".globl host_isr_12",
    "host_isr_12:",
    "push 12",
    "jmp host_generic_interrupt",
    ".globl host_isr_13",
    "host_isr_13:",
    "push 13",
    "jmp host_generic_interrupt",
    ".globl host_isr_14",
    "host_isr_14:",
    "push 14",
    "jmp host_generic_interrupt",
    ".globl host_isr_16",
    "host_isr_16:",
    "push 0",
    "push 16",
    "jmp host_generic_interrupt",
    ".globl host_isr_17",
    "host_isr_17:",
    "push 17",
    "jmp host_generic_interrupt",
    ".globl host_isr_18",
    "host_isr_18:",
    "push 0",
    "push 18",
    "jmp host_generic_interrupt",
    ".globl host_isr_19",
    "host_isr_19:",
    "push 0",
    "push 19",
    "jmp host_generic_interrupt",
    ".globl host_isr_20",
    "host_isr_20:",
    "push 0",
    "push 20",
    "jmp host_generic_interrupt",
    ".globl host_isr_30",
    "host_isr_30:",
    "push 30",
    "jmp host_generic_interrupt",
    dispatch = sym crate::host_isr::dispatch_host_interrupt,
);
